### ISSUE TITLE
Trajectory Semantic Clustering

### ISSUE THREAD

**Issue by dolongbien** [mie-lab/location-prediction#2]
Hi,

Thank you for your research and for publishing this code. I'm reproducing your experiment on the Foursquare dataset and have some questions (not technical ones):

1. The output of your model is the next location. What changes should I make to output clusters of user trajectory movement semantically? For example, two users do not necessarily have to be in the same physical trajectory to be in the same cluster, but rather in the same semantic context (home, work, etc.). 
2. Instead of next-location prediction, do you have any idea of using a seq2seq autoencoder to encode trajectory features, and then cluster them using K-MEANS or something?

I would appreciate your help with this.

**Comment by hongyeehh** [comment]
Hi, Thanks for your interest in the research. I provide the answers below (according to the best of my understanding):

- A straightforward adoption is to change the location embedding to an activity embedding, and instead of the location identifier, you input the activity label of each record. This will arguably simplify the model, and you might want to reduce the model's capacity (e.g., layers, heads)
- You might want to check out works with the keywords `trajectory embedding`. For the MHSA network, you can take the vector given in the last layer (the one before softmax) and regard it as a trajectory representation, just that the representation is optimized for next location prediction and not for, e.g., user profiling.
