### ISSUE TITLE
Running model for inference

### ISSUE THREAD

**Issue by adonnini** [mie-lab/location-prediction#8]
Hi,
I was able to successfully train the model using my dataset.
Now, I would like to run it for inference on production datasets produced by my application.
How do I do that? Should I simply run
```    python preprocessing/geolife.py 20```
and
```python main.py config/geolife/transformer.yml```
on production datasets?
Thanks

**Comment by hongyeehh** [comment]
Validation and Test results should be given as an output by running `main.py`, e.g., see [line 26](https://github.com/mie-lab/location-prediction/blob/3417149da1e1e47ac9c5dfe5b557b19e33e96c96/main.py#L26)

**Comment by adonnini** [comment]
@hongyeehh Thanks. I am sorry. My question was not clear.
If I understand correctly your statement above, in production to continue training and runf the model for inference I continue doing what is stated in
https://github.com/mie-lab/location-prediction#3-preprocess-the-dataset
and
https://github.com/mie-lab/location-prediction#4-run-the-proposed-transformer-model
Is my understanding correct?

FYI, I am using executorch to lower the model to Android devices.

If my understanding is correct, you can consider this issue closed.

Thanks for our help,

Alex Donnini

**Comment by hongyeehh** [comment]
Your inference dataset shall be in the same format as the training dataset, so you are right: executing `python preprocessing/geolife.py 20` (with an adjustment on your dataset) will ensure both have the same format. 

Instead of running `python main.py config/geolife/transformer.yml`, which will train the prediction network from scratch on the inference dataset, you should load the already trained network and freeze its parameters. For this, you can use the code within `get_test_result()` for reference.
